name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  docker-push:
    env:
      IMAGE_NAME: "carrier/vantage6-test-algorithms"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ secrets.CARRIER_HARBOR_SERVER }}
          username: ${{ secrets.CARRIER_HARBOR_USER }}
          password: ${{ secrets.CARRIER_HARBOR_PASSWORD }}

      - name: Create image name
        run: >
          echo NAME=${{ secrets.CARRIER_HARBOR_SERVER }}/${{ env.IMAGE_NAME }}:parquet >> $GITHUB_OUTPUT
        id: complete_image_name

      - name: Build the Docker image
        run: docker build . --file Dockerfile.parquet --tag ${{ steps.complete_image_name.outputs.NAME }}

      - name: Push the Docker image
        run: docker push ${{ steps.complete_image_name.outputs.NAME }}

      - name: Retrieve the vantage6 client version
        id: v6_version
        run: >
          docker run ${{ steps.complete_image_name.outputs.NAME }} python -m pip list| 
          grep vantage6-client| sed 's/vantage6-client    /TAG=v6-/g' >> $GITHUB_OUTPUT

      - name: Create extended image name
        id: extended_name
        run: >
          echo NAME=${{ steps.complete_image_name.outputs.NAME }}_${{ steps.v6_version.outputs.TAG}} >> $GITHUB_OUTPUT

      - name: Tag with vantage version
        run: >
          docker tag ${{ steps.complete_image_name.outputs.NAME }} ${{ steps.extended_name.outputs.NAME }}
      - name: push tagged version
        run: >
          docker push ${{ steps.extended_name.outputs.NAME }}
