name: Docker Image CI

on:
  push:
    branches: [ master ]
    
jobs:

  docker-push:
    env:
      IMAGE_NAME: "/carrier/vantage6-test-algorithms"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      #run: echo '${{ secrets.HARBOR_PASSWORD }}' | docker login ${{env.HARBOR_SERVER}} --username '${{ secrets.HARBOR_USER }}' --password-stdin
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ secrets.CARRIER_HARBOR_SERVER }}
        username: ${{ secrets.CARRIER_HARBOR_USER }}
        password: ${{ secrets.CARRIER_HARBOR_PASSWORD }}
        
    - name: Create image name
      run: echo ${{ secrets.CARRIER_HARBOR_SERVER }}/${{ env.IMAGE_NAME }}
      id: complete_image_name
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.complete_image_name.outputs }}

    - name: Push the Docker image
      run: docker push $IMAGE_NAME
